name: Hapi Now Auth Test Runner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
  steps:
    - uses: actions/checkout@v2
    - name: Node ${{matrix.node}} test
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node}}
    - run: npm install
    - run: npm test