name: Hapi Now Auth Test Runner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Node ${{matrix.node}} test
  steps:
  - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
    with:
      node-version: ${{matrix.node}}
  - run: npm install
  - run: npm test